using System;
using System.Collections.Generic;

namespace WPF_test
{

    public class TypeFunctionList : List<Char>
    {
        public TypeFunctionList()

        {
            this.Add('A');
            this.Add('E');
            this.Add('O');
            this.Add(' ');
        }
    }
    public class FunctionList : List<String>
    {
        public FunctionList()
        {
            this.Add("E Commands (DO something)");
            this.Add("");
            this.Add("------");
            this.Add("LINK");
            this.Add("SAY");
            this.Add("STORE_OPEN");
            this.Add("ROB_ITEM");
            this.Add("GIVE_ITEM");
            this.Add("BBS_OPEN");
            this.Add("CHANGE_HP");
            this.Add("CHANGE_MP");
            this.Add("CHANGE_STR");
            this.Add("CHANGE_DEX");
            this.Add("CHANGE_INT");
            this.Add("CHANGE_WIS");
            this.Add("CHANGE_CHA");
            this.Add("CHANGE_STR");
            this.Add("CHANGE_CON");
            this.Add("SHOW_MAGIC");
            this.Add("MAKER_OPEN");
            this.Add("STORAGE_OPEN");
            this.Add("AUCTION_SELL_OPEN");
            this.Add("AUCTION_BUY_OPEN");
            this.Add("SELECT_MSG");
            this.Add("MESSAGE_OK");
            this.Add("MESSAGE_NONE");
            this.Add("GIVE_GOLD");
            this.Add("ROB_GOLD");
            this.Add("RUN_EVENT");
            this.Add("ADD_EVENT");
            this.Add("DEL_EVENT");
            this.Add("RAND_SAY");
            this.Add("RETURN");
            this.Add("CHANGE_MAGETYPE");
            this.Add("GUILD_OPEN");
            this.Add("REPAIR_ITEM_OPEN");
            this.Add("GIVE_SPECIAL_ATTACK");
            this.Add("KILL_NPC");
            this.Add("PLUS_MORAL");
            this.Add("OPEN_CONTRIBUTION");
            this.Add("CHANGE_STORAGE_TYPE");
            this.Add("WARP_GATE");
            this.Add("AUCTION_DRAW_NOBID");
            this.Add("AUCTION_DRAW_NOBUY");
            this.Add("AUCTION_BUY_ITEM");
            this.Add("AUCTION_GET_MONEY");
            this.Add("AUCTION_DELETE_BADLIST");
            this.Add("CHANGE_MAX_HP");
            this.Add("CHANGE_MAX_MP");
            this.Add("CHANGE_MAX_STM");
            this.Add("CHANGE_MAX_WGT");
            this.Add("OPEN_HAIRSHOP");
            this.Add("LIVE_NPC");
            this.Add("ADD SERVER_EVENT");
            this.Add("DEL SERVER_EVENT");
            this.Add("GIVE_MAKE_SKILL");
            this.Add("OPEN_SPECIAL_MAKESKILL");
            this.Add("GUILDTOWN_TAXRATE");
            this.Add("OPEN_GUILDTOWN_STORE_REG");
            this.Add("OPEN_GUILDTOWN_STORE");
            this.Add("MAGIC");
            this.Add("SPECIAL_ATTACK");
            this.Add("OPEN_TRADER");
            this.Add("OPEN_CHANGE_ITEM");
            this.Add("COUNTER_START");
            this.Add("COUNTER_INIT");
            this.Add("OPEN_MONSTER_SELECT");
            this.Add("TIMER_START");
            this.Add("TIMER_INIT");
            this.Add("SET_EVENTCOUNT");
            this.Add("CLASSPOINT_STORE_OPEN");
            this.Add("XMASPOINT_USER");
            this.Add("XMASPOINT_GUILD");
            this.Add("------");
            this.Add("A / O Commands (CHECK/REQUIRE or SET(O) something");
            this.Add("------");
            this.Add("LEVEL");
            this.Add("GENDER");
            this.Add("AGE");
            this.Add("HP");
            this.Add("MP");
            this.Add("STR");
            this.Add("DEX");
            this.Add("INT");
            this.Add("WIS");
            this.Add("CHA");
            this.Add("CON");
            this.Add("DMAGIC");
            this.Add("WMAGIC");
            this.Add("BMAGIC");
            this.Add("SWORD");
            this.Add("SPEAR");
            this.Add("AXE");
            this.Add("STR");
            this.Add("BOW");
            this.Add("KNUCKLE");
            this.Add("STAFF");
            this.Add("WEAPONMAKE");
            this.Add("ARMORMAKE");
            this.Add("ACCMAKE");
            this.Add("POTIONMAKE");
            this.Add("COOKING");
            this.Add("EXIST_ITEM");
            this.Add("ABSENT_ITEM");
            this.Add("EXIST_ITEM_TYPE");
            this.Add("ABSENT_ITEM_TYPE");
            this.Add("EXIST_MAGIC");
            this.Add("ABSENT_MAGIC");
            this.Add("EXIST_EVENT");
            this.Add("ADD_EVENT");
            this.Add("TIME");
            this.Add("RAND");
            this.Add("GOLD");
            this.Add("GAME_TIME");
            this.Add("GAME_DAY");
            this.Add("GAME_MONTH");
            this.Add("HOWMUCH_ITEM");
            this.Add("MORAL");
            this.Add("MAGETYPE");
            this.Add("WEIGHT");
            this.Add("RANK");
            this.Add("CHECK_ITEMSLOT");
            this.Add("CHECK_POSITION");
            this.Add("CHECK_FIRST_CLICK");
            this.Add("STORAGE_TYPE");
            this.Add("CHECK_AUCTION_BADLIST");
            this.Add("CHECK_AUCTION_STATE");
            this.Add("EXIST_SPECIAL_ATTACK");
            this.Add("ABSENT_SPECIAL_ATTACK");
            this.Add("EXIST_MAGETYPE");
            this.Add("ABSENT_MAGETYPE");
            this.Add("CHECK_ALIVE_NPC");
            this.Add("EXIST_MAKE_SKILL");
            this.Add("ABSENT_MAKE_SKILL");
            this.Add("CHECK_GUILD_TOWN");
            this.Add("CHECK_GUILD_RANK");
            this.Add("COMPARE_BASIC_VALUE");
            this.Add("CHECK_JOB");
            this.Add("CHECK_GUILD_TOWN_ALLY");
            this.Add("CHECK_GUILD_TOWN_WAR");
            this.Add("CHECK_GUILD_TOWN_LEVEL");
            this.Add("CHECK_HUMAN");
            this.Add("CHECK_DEMON");
            this.Add("MONSTER");
            this.Add("CHECK_COUNTER");
            this.Add("CHECK_MONSTER");
            this.Add("CHECK_TIIMER");
            this.Add("CHECK_EVENTCOUNT");
            this.Add("CHECK_PAYTYPE");
            this.Add("CHECK_CLASS_TOWN");
            this.Add("CHECK_CLASS_TOWN_WAR");
            this.Add("CHECK_HAVE_EVENTBOOK");
            this.Add("CHECK_EVENTBOOK");
            this.Add("CHECK_PKMODE");
            this.Add("CHECKPAYACCOUNT");
            this.Add("PAYACCOUNT");

        }
    }
}